---
 - name: Playbook to install tools
   hosts: all
   tasks:
    - name: Install Tools
      win_chocolatey:
       name: 
        - git
        - notepadplusplus
        - 7zip
        - putty
        - winscp
        - googlechrome
        - azure-cli
       state: present