- hosts: debian
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      autoremove: yes
      purge: yes
      cache_valid_time: 86400 
